name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' or your deploy branch

permissions:
  contents: write  # required for GH Pages deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Match your project

      - name: Install dependencies
        run: npm install
        working-directory: frontend/learniverse-connect

      - name: Build project
        run: npm run build
        working-directory: frontend/learniverse-connect

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/learniverse-connect/dist
